"""
Calculator module (AI-generated docstrings)

This module provides basic arithmetic operations. The module-level docstring
and individual function docstrings were generated by an AI assistant and aim to
be concise and consistent. Review and adapt them as needed for teaching or
production use.
"""

from typing import Union

Number = Union[int, float]


def add(a: Number, b: Number) -> Number:
    """
    Return the sum of two numbers.

    Parameters
    ----------
    a : int or float
        First operand.
    b : int or float
        Second operand.

    Returns
    -------
    int or float
        Sum of a and b.
    """
    if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):
        raise TypeError("Arguments must be numeric (int or float)")
    return a + b


def subtract(a: Number, b: Number) -> Number:
    """
    Return the difference between two numbers.

    Parameters
    ----------
    a : int or float
        Value to subtract from.
    b : int or float
        Value to subtract.

    Returns
    -------
    int or float
        Result of a - b.
    """
    if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):
        raise TypeError("Arguments must be numeric (int or float)")
    return a - b


def multiply(a: Number, b: Number) -> Number:
    """
    Multiply two numeric values and return the product.

    Parameters
    ----------
    a : int or float
        First multiplicand.
    b : int or float
        Second multiplicand.

    Returns
    -------
    int or float
        Product of a and b.
    """
    if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):
        raise TypeError("Arguments must be numeric (int or float)")
    return a * b


def divide(a: Number, b: Number) -> float:
    """
    Divide a by b and return the quotient as a float.

    Parameters
    ----------
    a : int or float
        Numerator.
    b : int or float
        Denominator.

    Returns
    -------
    float
        Floating-point result of a / b.

    Raises
    ------
    ZeroDivisionError
        If b is zero.
    """
    if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):
        raise TypeError("Arguments must be numeric (int or float)")
    if b == 0:
        raise ZeroDivisionError("Division by zero")
    return a / b


if __name__ == "__main__":
    # Run a set of example calculations
    print("Running AI-documented calculator examples:\n")
    print(f"add(4, 5) = {add(4,5)}")
    print(f"subtract(10, 2) = {subtract(10,2)}")
    print(f"multiply(3, 7) = {multiply(3,7)}")
    print(f"divide(9, 3) = {divide(9,3)}")
